#!/usr/bin/python3


import os
import time

from PIL import Image, ImageSequence


def narrow_gif(path):
    gif = Image.open(path)
    width, weight = gif.size
    print('origin size', width, weight)

    duration = gif.info['duration']

    images = [f.copy() for f in ImageSequence.Iterator(gif)]

    images_list = []
    os.mkdir("images")

    # rate = 0.25
    # width_new, weight_new = width * rate, weight * rate

    width_new, weight_new = 128, 128
    for index, frame in enumerate(images):
        frame.save("./images/%d.png" % index)

        im = Image.open("./images/%d.png" % index)
        im.thumbnail((width_new, weight_new), Image.ANTIALIAS)

        images_list.append(im)

    os.system("rm -rf ./images")

    # out = '{}/{}.gif'.format('/'.join(path.split('/')[:-1]), str(int(time.time())))
    out = path
    images_list[0].save(out, 'gif', save_all=True, append_images=images_list[1:], loop=0, duration=duration)
    #
    image = Image.open(path)
    width, weight = image.size
    print('current size', width, weight)


def narrow_image(path):
    image = Image.open(path)
    width, weight = image.size
    print('origin size', width, weight)

    # rate = 0.25
    # width_new, weight_new = width * rate, weight * rate
    width_new, weight_new = 128, 128
    image.thumbnail((width_new, weight_new), Image.ANTIALIAS)
    # dImg = sImg.resize((w / 2, h / 2), Image.ANTIALIAS)

    # out = '{}/{}.png'.format('/'.join(path.split('/')[:-1]), str(int(time.time())))
    out = path
    image.save(out, path.split('.')[-1])
    #
    image = Image.open(path)
    width, weight = image.size
    print('current size', width, weight)


def main(path):
    path = path.strip()

    form = dict(
        gif=narrow_gif,
        png=narrow_image,
        jpg=narrow_image,
        jpeg=narrow_image,
    )

    suffix = path.split('.')[-1]
    func = form.get(suffix)
    if func is None:
        print('error, only can process gif, png, jpg, jpeg')
    else:
        func(path=path)
        print('success')


if __name__ == '__main__':
    path = input('please input image path\n')
    main(path=path)
